name: Deployment

on:
  push:
    branches: [hexo]

jobs:
  hexo-deployment:
    runs-on: ubuntu-latest
    env:
      TZ: Asia/Shanghai

    steps:
    - name: Checkout source
      uses: actions/checkout@v2
      with:
        submodules: true

    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '16.x'

    - name: Install dependencies & Generate static files
      run: |
        node -v
        npm i -g hexo-cli
        npm i
        hexo clean
        hexo g
    - name: Deploy to Github Pages
      env:
        GIT_NAME: LeUKi
        GIT_EMAIL: ${{ secrets.GIT_EMAIL }}
        REPO: github.com/LeUKi/LeUKi.github.io
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
      run: |
        mkdir TEMP && mv root/* TEMP && mv public TEMP/docs && cd TEMP && git init && git add .
        git config --global user.name $GIT_NAME
        git config --global user.email $GIT_EMAIL
        git commit -m "Site deployed by GitHub Actions"
        git push --force --quiet "https://$GH_TOKEN@$REPO" master:main